config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "categories#index"
  get "/home", to: "home#index", as: "home"
  resources :users, only: [:splash]
  resources :categories, only: [:index, :new, :create, :edit, :update, :destroy], :path => "categories" do 
    resources :expenses, only: [:index, :new, :create, :edit, :update, :destroy], :path => "transactions"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_expenses, dependent: :destroy
  has_many :expenses, through: :category_expenses
  validates :name, presence: true
  # validates :icon, presence: true

  def total_amount
    expenses.sum(&:amount)
  end
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  belongs_to :category
  belongs_to :expense
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  has_many :category_expenses, dependent: :destroy
  has_many :categories, through: :category_expenses

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :expenses, dependent: :destroy
  has_many :categories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    categories_url
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update destroy]
  before_action :set_user, only: %i[index edit create update destroy]

  # GET /categories or /categories.json
  def index
    if user_signed_in?
      @page_title = 'Categories'
      @categories = Category.includes(:expenses).where(user: current_user)
      @total = Expense.where(user: current_user).sum(&:amount)
    else
      @page_title = 'Welcome'
      redirect_to home_path
    end
  end

  # GET /category/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(**category_params)
    @category.user = current_user

    if @category.save
      redirect_to categories_url, notice: 'Category was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    if @category.update(category_params)
      redirect_to categories_url, notice: 'Category was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  def set_category
    @category = set_user.categories.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[edit update destroy]
  before_action :set_category, only: %i[index new edit create update destroy]
  before_action :set_user, only: %i[index edit create update destroy]
  # GET /expenses or /expenses.json
  def index
    @expenses = @category.expenses.order(created_at: :desc)
  end

  # GET category/expenses/new
  def new
    @expense = Expense.new
  end

  # GET category/expenses/1/edit
  def edit; end

  # POST category/expenses
  def create
    @expense = Expense.new(**expense_params)
    @expense.user = current_user
    if @expense.save
      @category_expense = CategoryExpense.create(category: @category, expense: @expense)
      redirect_to category_expenses_url(@category), notice: 'Expense was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT category/expenses/1
  def update
    if @expense.update(expense_params)
      redirect_to category_expenses_url, notice: 'Expense was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE category/expenses/1
  def destroy
    @expense.destroy
    redirect_to category_expenses_url(@category), notice: 'Expense was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  def set_category
    @category = set_user.categories.find(params[:category_id])
  end

  def set_expense
    @expense = set_user.expenses.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def splash
    if current_user
      redirect_to categories_url, alert: "You are already logged in as, #{current_user.name}"
    else
      render :index
    end
  end

  def index
    @user = current_user
  end

  def redirect_to_categories
    redirect_to categories_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
    <% if category.errors.any? %>
      <div id="error_explanation" class="msg-error">
        <h2> There are: <%= pluralize(category.errors.count, "error") %>: </h2>
  
        <ul>
          <% category.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field form-outline mb-2">
      <%= form.label :name %>
      <%= form.text_field :name, class: "orm-control" %>
    </div>
  
    <div class="field">
      <%= form.label :icon %>
      <%= form.text_field :icon, class: "orm-control" %>
    </div>
  
    <div class="inline">
    </div>
  
    <div class=" form-outline ">
      <%= form.submit "#{action_name == 'edit' ? 'Update' : 'Save'}", class: "" %>
    </div>
  <% end %>

app/views/categories/edit.html.erb
<% content_for :title, 'My-Exp | New Category' %>
<section class="container authentication">
  <h1 class="text-main-header">Editing <%=@category.name %></h1>

  <%= render "form", group: @category %>
  <%= link_to "Back to categories", groupies_path, class: "" %>
</section>

app/views/categories/index.html.erb
<% content_for :title, 'MoneyMate | Categories' %>
  <%= javascript_import_module_tag "menu" %>

<div class="grand-total">
        <p class="amount-label">Total Amount</p>
        <p class="amount"><%= "$#{@total}" %></p>
</div>
    <div class="container-fuild mx-2">
    <% if @categories.present? %>
    
    <% @categories.each do |category| %>   
       
          <%= link_to  category_expenses_path(category), class: "card-link" do %>
            <div class="card"> 
              <div class="text-container">
                <%= image_tag(category.icon, class: "icon") %>
                <div class="contenu">
                  <h4 class="text-lg">
                    <%= category.name %>
                  </h4>
                  <div class="amount">
                    <%= "$#{category.total_amount}" %>
                  </div>
                </div>
                
              </div>
              <p class="text-xs px-2"><%= category.created_at.strftime("%d %b %Y") %></p>
            </div>
          <% end %>
          <% end %>
    <% else %>
        <div class="actions">
            You don't have any category yet! Create one.
        </div>
    <% end %>

    <div class = "btn-wrapper">
      <%= link_to new_category_path, class: 'btn-add' do %>
        <span class = "btn-spacer"> Add category </span>
        <%= image_tag('https://img.icons8.com/color-glass/30/null/plus-2-math.png', class:"back-arrow") %>
        <% end %>
    </div>
</div>

app/views/categories/new.html.erb
<% content_for :title, 'My-Exp | New Category' %>
<section class="container authentication">
  <h1 class="text-main-header">New Category</h1>

  <%= render "form", category: @category %>
  <%= link_to 'Back to categories', categories_path, class: "" %>
</section>

app/views/expenses/_form.html.erb
<%= form_with(model: expense, url: "#{action_name == 'edit' ? category_expense_path(@category, expense) : category_expenses_path(@category)}", class: "contents") do |form| %>
  <% if expense.errors.any? %>
    <div id="error_explanation" class="msg-error">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "" %>
  </div>

  <div class="field ">
    <%= form.label :amount %>
    <%= form.number_field :amount, step: ".01", class: "" %>
  </div>

  <div class="">
    <%= form.submit "#{action_name == 'edit' ? 'Update' : 'Save'}"%>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<% content_for :title, 'My-Exp | Transactions' %>
<section class="container authentication">
  <h1 class="font-bold text-4xl">Editing expense</h1>

  <%= render "form", expense: @expense %>
  <%= link_to "Back to expenses", category_expenses_path, class: "" %>
</section>

app/views/expenses/index.html.erb
<% content_for :title, "Carpe Diem | #{@category.name} Transactions" %>
<div class="w-full">
  <div class="grand-total with-img">
    <div class= "header-img-wrapper">
      <img src="<%= @category.icon %>" alt=" category image" class="card-img circle" />
    </div>
      <h2 class="amount-label"><%= @category.name %></h2>
      <p class="amount"> <%= "$#{@category.total_amount}" %> </p>
    </div>
  </div>

  <div id="expenses" class="container-fuild m-3">
  <% if @expenses.present? %>
    <% @expenses.each do |expense| %>
        <div id="<%= dom_id expense %>" class="card exp mb-2">
              <div class=" transaction d-flex justify-content-center align-items-center">
                <div class="flex-row">
                  <h4 class="text-lg">
                    <%= expense.name %>
                  </h4>
                </div>
                  <% if action_name != "show" %>
                  <div>
                      <%= link_to edit_category_expense_path(@category, expense), class: "btn-icons" do %>
                        <%= image_tag('edit-icon.png', class:"btn-icon") %>
                      <% end %>
                      <%= button_to category_expense_path(@category, expense), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, class: "btn-clean" do %>
                        <%= image_tag('trash-icon.png', class:"btn-icon") %>
                      <% end %>
                  </div>
              <% end %>
                <div> 
                 <span class="amount">$<%= expense.amount %> </span>
                 </div>
              </div>
                
            </div>
            <% end %>
        
        </div>
        </div>
  </div>
</div>

<% else %>
<div class="text-center p-4">
        You don't have any transaction yet! Create one.
    </div>
    
  <% end %>

<div class="btn-wrapper">
  <%= link_to new_category_expense_path, class: "btn-add" do %>
    <span class = "btn-spacer"> New transaction </span>
        <%= image_tag('add.png', class:"back-arrow") %>
    </div>
  <% end %>
</div>

app/views/expenses/new.html.erb
<% content_for :title, 'Carpe Diem | New Transaction' %>
<section class="container authentication">
  <h1 class="text-main-header"> New Transaction for <%= @category.name %> category </h1>

  <%= render "form", expense: @expense %>
  
  <%= link_to 'Back to expenses', category_expenses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</section>

app/views/home/index.html.erb
<% content_for :title, 'MoneyMate' %>
<section>
    <% if user_signed_in?%>
    <div>
    <h1>hello <%= @user.email %> </h1>
    <%= button_to "log_out", destroy_user_session_path , method: :delete %>
    </div>
<%else%>
    <div class = "container d-flex align-items-center flex-column justify-content-center mb-4">
    <%= image_tag 'background.png', class:"mb-4" %>
        <div class="d-flex align-items-center flex-column justify-content-center">
            <%= link_to "Login", new_user_session_path, class: "btn btn-primary mb-4 w-100" %>
             <%= link_to "sign_up", new_user_registration_path, class: "btn btn-success mb-4 w-100"%>
        </div>
     </div>
<%end%>

</section>
        

app/views/layouts/_navbar.html.erb
<nav>
  <div class="top-nav">
  
      <% if controller_name == 'categories' and action_name == 'index' %>
        <a class="hamburger" href="#" id="popup-menu-button">
          <%= image_tag('hamburger4.png', id:"burger-btn") %>
        </a>
       
      <% elsif controller_name == 'categories' and action_name != 'index' %>
      <div class="hamburger">
      <%= link_to categories_path do %>
        <%= image_tag('back-btn-white2.png', class:"back-arrow") %>
      <% end %>
    </div>
  <% elsif controller_name == 'expenses' %>
  
    <div class="back-btn">
      <%= link_to "#{action_name == 'index' ? categories_path : category_expenses_path}" do %>
      
      <%= image_tag('back-btn-white2.png', class:"back-arrow") %>
      <% end %>
    </div>
  <% end %>
      <h1 class="text-main-header">
        <% if controller_name == 'expenses' %>
          <%= 'Transactions' %>
        <% else %>
          <%= 'Categories' %>
        <% end %>
      </h1>
      <div class="search">
        <%= image_tag('search2.png', class:"back-arrow") %>
      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoneyMate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
  
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'menu' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<main>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
   
    <% if current_user %>
      <%= render 'layouts/navbar' %>
    <% end %>
    
    <%= yield %>

    <div id="popup-menu">
      <ul class="menu-layout">
        <li calss= "logout"> 
        
          <%= button_to destroy_user_session_path, method: :delete, id: "home-form", class: 'btn-clean btn-nav menu-item' do %>
              <span calss= "logout"> Logout </span>
              <%= image_tag('https://img.icons8.com/external-sbts2018-flat-sbts2018/30/null/external-logout-social-media-basic-1-sbts2018-flat-sbts2018.png', class:"logout-icon") %>
          <% end %>
        </li>
        <li>
          <%= button_to edit_user_registration_path, method: :get, id: "home-form2", class: 'btn-clean btn-nav menu-item' do %>
            <span calss= "logout"> Update </span>
            <%= image_tag('https://img.icons8.com/external-xnimrodx-blue-xnimrodx/30/null/external-setting-advertising-xnimrodx-blue-xnimrodx.png', class:"logout-icon") %>
          <% end %>
        </li>

      
      </ul>
    </div>
   
  </main>
  </body>
</html>